### PR TITLE
Add PHP "Hello_World"

### PR DESCRIPTION
**Pull request by ca-kraa**

### CODE REVIEW

**Review by dev-AshishRanjan — APPROVED** [review]
LGTM!

**Comment by dev-AshishRanjan** [comment]
If you have projects on HTML+CSS+JS techstack you can contribute to [Hacktoberfest-frontend](https://github.com/dev-AshishRanjan/Hacktoberfest-frontend)

You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.

Happy Contributing season!
Keep up the good work!

**Comment by ca-kraa** [comment]
Oke Thanks Sir

**Comment by ca-kraa** [comment]
> If you have projects on HTML+CSS+JS techstack you can contribute to [Hacktoberfest-frontend](https://github.com/dev-AshishRanjan/Hacktoberfest-frontend)
> 
> You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.
> 
> Happy Contributing season! Keep up the good work!

Btw can I use framework CSS? for CSS?

**Comment by dev-AshishRanjan** [comment]
> > If you have projects on HTML+CSS+JS techstack you can contribute to [Hacktoberfest-frontend](https://github.com/dev-AshishRanjan/Hacktoberfest-frontend)
> > You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.
> > Happy Contributing season! Keep up the good work!
> 
> Btw can I use framework CSS? for CSS?

Ig **no**, but you can use the final compiled css of those frameworks.
I suggest to use the css(.css) files, it doesn't matter if it's self written or compiled (compiled on your local system but the compiled file is pushed to the repo) file

**Pull request merged**
